config/routes.rb
Rails.application.routes.draw do

  root 'rides#index'

  resources :rides

end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :user
  belongs_to :taxi_provider

  validates :taxi_provider, presence: { message: 'Taxi provider can\'t by blank.' }
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 10000 }
  validates :distance, presence: true, numericality: { greater_than: 0, less_than: 10000 }

  validates :origin, presence: true, location_format: { message: 'origin location has invalid format.' }
  validates :destination, presence: true, location_format: { message: 'destination location has invalid format.' }

  before_validation :calculate_distance

  scope :stats_from, -> (date) { select('rides.created_at, sum(rides.distance) as distance_sum, avg(rides.distance) as distance_avg, avg(rides.price) as price_avg, group_concat(DISTINCT taxi_providers.name) as taxi_provider_names')
  									.joins(:taxi_provider)
  									.where(created_at: date..Time.zone.now.end_of_day).group('date(rides.created_at)') }

  # TODO
  # change callback + move to sidekiq if performance needed
  def calculate_distance
  	route = Route.new(origin: origin, destination: destination)
  	self.distance = route.distance.to_f
  end

end

app/models/route.rb
class Route

	attr_accessor :origin, :destination

	API_KEY = 'AIzaSyCMhZ4FD0FSENSoUumNgosUTbDfYNtmvN0'

	def initialize(options = {})
		self.origin = options[:origin]
		self.destination = options[:destination]
	end

	def results
		require 'rest-client'
		url = "https://maps.googleapis.com/maps/api/distancematrix/json?key=#{API_KEY}"
		response = RestClient.get url, { params: { origins: origin, destinations: destination } }
		JSON.parse(response.body)
	end

	def distance
		data = results
		data['rows'].first['elements'].first['distance']['text']
	rescue
		raise 'Distance calculation fails'
	end

end

app/models/taxi_provider.rb
class TaxiProvider < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :rides
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find_or_create_by(token: token)
  end

  def token
  	return cookies[:token] unless cookies[:token].blank?
  	require 'securerandom'
  	loop do
  		generated_token = SecureRandom.hex
  		next if User.exists?(token: generated_token)
  		cookies[:token] = generated_token
  		break
  	end
  	cookies[:token]
  end

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

	def index
		@rides = current_user.rides.stats_from(Date.today.at_beginning_of_month)
	end

	def new
		@ride = Ride.new
	end

	def create
		@ride = Ride.new(ride_params)
		if @ride.valid? && @ride.save
			redirect_to new_ride_path, flash: { notice: 'Ride successfully added.' }
		else
			render :new
		end
	end

	private

	def ride_params
		params.require(:ride)
			  .permit(:taxi_provider_id, :price, :origin, :destination)
			  .merge(user_id: current_user.id)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Riderank</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
	<div class="flash">
		<% flash.each do |key, value| %>
		  <%= content_tag :div, value, class: "flash #{key}" %>
		<% end %>
	</div>
	<%= yield %>
</div>
</body>
</html>

app/views/rides/index.html.erb
<% if @rides.empty? %>
	<p>No rides in this month<p>
<% else %>
	<table>
		<thead>
			<th>Day</th>
			<th>Rides sum</th>
			<th>Avg. ride</th>
			<th>Avg. price</th>
			<th>Taxis</th>
		</thead>
		<tbody>
			<% @rides.each do |ride| %>
				<tr>
					<td><%= ride.created_at.strftime('%B, %eth') %></td>	
					<td><%= number_with_precision(ride.distance_sum, precision: 2, strip_insignificant_zeros: true) %> km</td>	
					<td><%= number_with_precision(ride.distance_avg, precision: 2, strip_insignificant_zeros: true) %> km</td>	
					<td><%= number_with_precision(ride.price_avg, precision: 2, strip_insignificant_zeros: true) %> EUR</td>	
					<td><%= ride.taxi_provider_names %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>
<br/>
<%= link_to 'Add ride', new_ride_path %>

app/views/rides/new.html.erb
<%= simple_form_for @ride do |f| %>
	<div>
		<%= f.input :origin %>
	</div>
	<div>
		<%= f.input :destination %>
	</div>
	<div>
		<%= f.input :price, input_html: { step: 0.01 } %>
	</div>
	<div>
		<%= f.association :taxi_provider %>
	</div>	
	<div>
		<%= f.submit 'Add ride' %>
	</div>
<% end %>
<br/>
<%= link_to 'ride stats', rides_path %>